### ISSUE TITLE
ERDDAP setup.xml no longer has some of the previous HTML related tags for styling/configuration of language switcher

### ISSUE THREAD

**Issue by jacobthompson101** [ioos/erddap-gold-standard#23]
I noticed on a recent commit the setup.xml was removed and re-added, but some of the usual HTML related tags were missing. I am not sure if this was intentional and if there are now other places to configure these options, a quick search of the code base did not bring up these previously set variable names.

Bob had recently pushed in version 2.14 the ability to use multilingual tags/shortcodes that are accessible to Google Translate on the fly. One issue is that I can no longer specify the language switcher in the following tag:
```<startBodyHtml5>
&loginInfo; | &language;
```

See a second example snippet of what I mean below, in terms of ERDDAP customization/styling for different organizations:
```
<startHeadHtml5><![CDATA[
<!DOCTYPE html>
...
<link href="/erddap/images/erddap2.css" rel="stylesheet" type="text/css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Global site tag (gtag.js) - Google Analytics -->
...
]]></startHeadHtml5>
```

**Comment by MathewBiddle** [comment]
I just updated from v2.11 to v2.18 and ran into this as well. A couple things I needed to do:
* Reviewed https://coastwatch.pfeg.noaa.gov/erddap/download/changes.html for all the changes between my version and the most recent version
   * A major change was a lot of the tags were moved from [setup.xml to dataset.xml with v2.00](https://coastwatch.pfeg.noaa.gov/erddap/download/changes.html#changes2.00). That is not reflected in the dataset.xml or setup.xml provided here. 
* Migrated the existing (appropriate) tags from setup.xml to datasets.xml as documented in the v2.00 changes. 
* Updated the new datasets.xml line from `      &loginInfo; &nbsp; &nbsp;` to `      &loginInfo; | &language; &nbsp; &nbsp;`
* Followed the rest of Bob's instructions for updating the html tags in [v2.15](https://coastwatch.pfeg.noaa.gov/erddap/download/changes.html#changes2.15).

Since there has been significant changes to datasets.xml and setup.xml since this gold standard repository was created. I think we need to update setup.xml and datasets.xml to reflect those changes and hopefully resolve these issues.
