### ISSUE TITLE
Add instructions for updating ERDDAP

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/erddap-gold-standard#8]
It would be good to include instructions on how to update ERDDAP when using this gold-standard deployment. Here are my thoughts on the process before I attempt it.

1. Check [docker-erddap](https://hub.docker.com/r/axiom/docker-erddap/tags) has the version you want to update to.
1. Review **Things ERDDAP Administrators Need to Know and Do** on the [ERDDAP Changes](https://coastwatch.pfeg.noaa.gov/erddap/download/changes.html) page.
   1. Be sure to review all of the topics listed between your deployed version and the one you want to update to. Some of the changes impact the various configuration files and as such should be addressed.
2. Stop the running docker container `docker-compose down`
3. Update image line in docker-compose.yml to point to appropriate version you want to update to: https://github.com/ioos/erddap-gold-standard/blob/b6c97291abe6bc9bdb80c664bb236e24e72269dc/docker-compose.yml#L5
4. Make the appropriate edits to the configuration files as researched in 1.
5. Spin up the new version `docker-compose up -d`

**Comment by abkfenris** [comment]
If you run `docker compose up` and don't have the specified image, it will pull it then. 

It won't check for if a tag has changed without explicitly re-pulling, say if you are using `latest` implicitly or explicitly.

**Comment by abkfenris** [comment]
You do need to update the `docker-compose.yml` with the new image tag.

Docker Compose will then pull the tag for you if you don't have it already, so you don't need to `docker pull`.

I was also trying to point out an edge case for usage of Docker Compose and Docker in general (but that mainly bites people using compose). Docker tags are mutable, so if you had `axiom/docker-erddap:latest` as the image in `docker-compose.yml` and wanted it to update when the upstream image was updated, then you do need to do an explicit `docker pull axiom/docker-erddap:latest`. If a tag isn't specified, `:latest` is implied, so that can work the same way.

**Comment by abkfenris** [comment]
Yes they are. 

I believe there was another conversation going around caused by folks getting in trouble using `latest` instead of being explicit when you created the issue, so I was trying to clarify how Docker deals with tag changes.

**Comment by MathewBiddle** [comment]
See https://ioos.github.io/erddap-gold-standard/update-erddap.html
